/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import databaseconnection.EmployeeQueries;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Employee;
import java.sql.SQLException;
import model.BookHouseKeeping;
import static model.BookHouseKeeping.bookedhousekeeper;
/**
 *
 * @author Shruti
 */
public class BookHousekeepingJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BookHousekeepingJPanel
     */
    public BookHousekeepingJPanel() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmployees = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        lblHouseKeepingEmail = new javax.swing.JLabel();
        txtHouseKeepingEmail = new javax.swing.JTextField();
        lblRole = new javax.swing.JLabel();
        txtRole = new javax.swing.JTextField();
        btnBook = new javax.swing.JButton();
        lblGuestEmail = new javax.swing.JLabel();
        txtGuestEmail = new javax.swing.JTextField();
        lblMsg = new javax.swing.JLabel();
        txtMsg = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        tblEmployees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEmployees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmployeesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEmployees);

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 51));
        jLabel2.setText("Book Housekeeping");

<<<<<<< HEAD (65d5c46) - merged conflict
                "Name", "Role", "email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
=======
                "Name", "Role", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
>>>>>>> origin/Shruti_Randive_002740632 (fdc8833

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         String housekeepemail = txthousekeepingemail.getText();
        String guest_email = txtguestemail.getText();
        String guest_housekeepername = txthousekeepername.getText();
        String guest_housekeeper_role = housekeeperrole.getText();

        String role=housekeeperrole.getText();
                
         // String city = lp.getCacity();
//         if(email.equals("")||guest_name.equals("")||guest_email.equals("")||role.equals(""))
//        {
//            JOptionPane.showMessageDialog(this, "Please add mandatory feild....");
//            return;
//        }
        
        bookedhousekeeper.add(new BookHouseKeeping(guest_housekeepername,housekeepemail,guest_email,guest_housekeeper_role));//String name, String email, String guest_name, String role
        
        JOptionPane.showMessageDialog(this, "Room Booked Successfully!!");
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tblEmployeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmployeesMouseClicked
        // TODO add your handling code here:
        int selectedRowIndex = tblEmployees.getSelectedRow();

        if (selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select a row to update");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblEmployees.getModel();

        Employee selectedGuest = (Employee) model.getValueAt(selectedRowIndex, 0);
        System.out.println(selectedGuest);

<<<<<<< HEAD (65d5c46) - merged conflict
        lblguestname.setText("Guest email");

        jButton2.setText("Book");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lblname.setText("House Keeping email");

        lbl_housekeepingemail.setText("HouseKeepername");

        lblrole.setText("role");
=======
        lblHouseKeepingEmail.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblHouseKeepingEmail.setForeground(new java.awt.Color(51, 153, 255));
        lblHouseKeepingEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/5340287_man_people_person_user_users_icon.png"))); // NOI18N
        lblHouseKeepingEmail.setText("Email:");

        txtHouseKeepingEmail.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        txtHouseKeepingEmail.setForeground(new java.awt.Color(51, 153, 255));

        lblRole.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblRole.setForeground(new java.awt.Color(51, 153, 255));
        lblRole.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/5340287_man_people_person_user_users_icon.png"))); // NOI18N
        lblRole.setText("Role:");

        txtRole.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        txtRole.setForeground(new java.awt.Color(51, 153, 255));

        btnBook.setBackground(new java.awt.Color(255, 153, 51));
        btnBook.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btnBook.setForeground(new java.awt.Color(255, 255, 255));
        btnBook.setText("Book");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });

        lblGuestEmail.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblGuestEmail.setForeground(new java.awt.Color(51, 153, 255));
        lblGuestEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/3586360_email_envelope_mail_send_icon.png"))); // NOI18N
        lblGuestEmail.setText("Guest Email:");

        txtGuestEmail.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        txtGuestEmail.setForeground(new java.awt.Color(51, 153, 255));

        lblMsg.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblMsg.setForeground(new java.awt.Color(51, 153, 255));
        lblMsg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/5340287_man_people_person_user_users_icon.png"))); // NOI18N
        lblMsg.setText("Message:");

        txtMsg.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        txtMsg.setForeground(new java.awt.Color(51, 153, 255));
>>>>>>> origin/Shruti_Randive_002740632 (fdc8833
    }//GEN-LAST:event_tblEmployeesMouseClicked

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        // TODO add your handling code here:
        String houseKeepingEmail = txtHouseKeepingEmail.getText();
        String guestEmail = txtGuestEmail.getText();
        String msg = txtMsg.getText();
        String role = txtRole.getText();
         
        bookedhousekeeper.add(new BookHouseKeeping(houseKeepingEmail,guestEmail,role,msg));
        JOptionPane.showMessageDialog(this, "House Keeping Booked Successfully!!");
    }//GEN-LAST:event_btnBookActionPerformed


    // Variables declaration - do not modify                     
}


<<<<<<< HEAD (65d5c46) - merged conflict
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblguestname, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblname)
                            .addComponent(lbl_housekeepingemail)
                            .addComponent(lblrole))
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtguestemail)
                            .addComponent(txthousekeepingemail)
                            .addComponent(housekeeperrole, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(txthousekeepername))))
                .addContainerGap(134, Short.MAX_VALUE))
=======
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(282, 282, 282)
                        .addComponent(btnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtGuestEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblGuestEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(271, 271, 271)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHouseKeepingEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHouseKeepingEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRole, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRole, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(141, Short.MAX_VALUE))
>>>>>>> origin/Shruti_Randive_002740632 (fdc8833
