/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JPanel;

/**
 *
 * @author user
 */
public class HotelJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public HotelJPanel() {
        initComponents();        
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddEmployees = new javax.swing.JButton();
        btnManageEmployees = new javax.swing.JButton();
        btnManageEmployees1 = new javax.swing.JButton();
        btnManageEmployees2 = new javax.swing.JButton();
        btnManageEmployees3 = new javax.swing.JButton();
        btnManageEmployees4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        btnAddEmployees.setBackground(new java.awt.Color(102, 204, 255));
        btnAddEmployees.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btnAddEmployees.setForeground(new java.awt.Color(255, 255, 255));
        btnAddEmployees.setText("ADD EMPLOYEES");

        btnManageEmployees.setBackground(new java.awt.Color(102, 204, 255));
        btnManageEmployees.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btnManageEmployees.setForeground(new java.awt.Color(255, 255, 255));
        btnManageEmployees.setText("ADD GUESTS");

        btnManageEmployees1.setBackground(new java.awt.Color(102, 204, 255));
        btnManageEmployees1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btnManageEmployees1.setForeground(new java.awt.Color(255, 255, 255));
        btnManageEmployees1.setText("MANAGE GUESTS");

        btnManageEmployees2.setBackground(new java.awt.Color(102, 204, 255));
        btnManageEmployees2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btnManageEmployees2.setForeground(new java.awt.Color(255, 255, 255));
        btnManageEmployees2.setText("MANAGE EMPLOYEES");
        btnManageEmployees2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEmployees2ActionPerformed(evt);
            }
        });

        btnManageEmployees3.setBackground(new java.awt.Color(102, 204, 255));
        btnManageEmployees3.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btnManageEmployees3.setForeground(new java.awt.Color(255, 255, 255));
        btnManageEmployees3.setText("MANAGE RECREATION ");
        btnManageEmployees3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEmployees3ActionPerformed(evt);
            }
        });

        btnManageEmployees4.setBackground(new java.awt.Color(102, 204, 255));
        btnManageEmployees4.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btnManageEmployees4.setForeground(new java.awt.Color(255, 255, 255));
        btnManageEmployees4.setText("ADD RECREATION ");
        btnManageEmployees4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEmployees4ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/istockphoto-1291294365-612x612.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddEmployees)
                            .addComponent(btnManageEmployees2)
                            .addComponent(btnManageEmployees4))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnManageEmployees3)
                            .addComponent(btnManageEmployees1)
                            .addComponent(btnManageEmployees)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2)))
                .addContainerGap(151, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAddEmployees, btnManageEmployees, btnManageEmployees1, btnManageEmployees2, btnManageEmployees3, btnManageEmployees4});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageEmployees2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageEmployees1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageEmployees3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageEmployees4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAddEmployees, btnManageEmployees, btnManageEmployees1, btnManageEmployees2, btnManageEmployees3, btnManageEmployees4});

    }// </editor-fold>//GEN-END:initComponents

    private void btnManageEmployees2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEmployees2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageEmployees2ActionPerformed

    private void btnManageEmployees3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEmployees3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageEmployees3ActionPerformed

    private void btnManageEmployees4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEmployees4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageEmployees4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEmployees;
    private javax.swing.JButton btnManageEmployees;
    private javax.swing.JButton btnManageEmployees1;
    private javax.swing.JButton btnManageEmployees2;
    private javax.swing.JButton btnManageEmployees3;
    private javax.swing.JButton btnManageEmployees4;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
