/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import databaseconnection.EmployeeQueries;
import databaseconnection.GuestQueries;
import databaseconnection.RecreationQueries;
import databaseconnection.TravelQueries;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.Employee;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class SchedulePickupJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AirportPickupJPanel
     */
    public SchedulePickupJPanel() {
        initComponents();
        populateDriverName();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblGuestEmail = new javax.swing.JLabel();
        txtGuestEmail = new javax.swing.JTextField();
        lblPickupLocation = new javax.swing.JLabel();
        txtPickupLocation = new javax.swing.JTextField();
        lblPickupTime = new javax.swing.JLabel();
        txtPickupTime = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        lblDriverName = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 51));
        jLabel2.setText("Schedule Airport Pickup");
        jPanel1.add(jLabel2);

        lblGuestEmail.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblGuestEmail.setForeground(new java.awt.Color(51, 153, 255));
        lblGuestEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/3586360_email_envelope_mail_send_icon.png"))); // NOI18N
        lblGuestEmail.setText("Guest Email:");
        jPanel1.add(lblGuestEmail);

        txtGuestEmail.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        txtGuestEmail.setForeground(new java.awt.Color(51, 153, 255));
        txtGuestEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtGuestEmailFocusLost(evt);
            }
        });
        txtGuestEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGuestEmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtGuestEmail);

        lblPickupLocation.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblPickupLocation.setForeground(new java.awt.Color(51, 153, 255));
        lblPickupLocation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/4200473_address_location_map_navigation_icon.png"))); // NOI18N
        lblPickupLocation.setText("Pickup Location:");
        jPanel1.add(lblPickupLocation);

        txtPickupLocation.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        txtPickupLocation.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.add(txtPickupLocation);

        lblPickupTime.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblPickupTime.setForeground(new java.awt.Color(51, 153, 255));
        lblPickupTime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/211606_clock_icon.png"))); // NOI18N
        lblPickupTime.setText("Pickup Time:");
        jPanel1.add(lblPickupTime);

        txtPickupTime.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        txtPickupTime.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.add(txtPickupTime);

        btnAdd.setBackground(new java.awt.Color(255, 153, 51));
        btnAdd.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Book");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd);

        lblDriverName.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblDriverName.setForeground(new java.awt.Color(51, 153, 255));
        lblDriverName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/5340287_man_people_person_user_users_icon.png"))); // NOI18N
        lblDriverName.setText("Driver Name:");
        jPanel1.add(lblDriverName);

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);

        jLayeredPane1.add(jPanel1, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 658, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLayeredPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 419, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLayeredPane1))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String guestEmail = txtGuestEmail.getText();
        String pickupLocation = txtPickupLocation.getText();
        String pickupTime = txtPickupTime.getText();
        String driverName = jTextField1.getText();
        String travel_type = "Schedule PickUp";
        
        TravelQueries tq = new TravelQueries();
        tq.schedulePickup(guestEmail, pickupLocation, pickupTime, travel_type, driverName);
        JOptionPane.showMessageDialog(this, "Schedule PickUp Successfull ");
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtGuestEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGuestEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGuestEmailActionPerformed

    private void txtGuestEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtGuestEmailFocusLost
        // TODO add your handling code here:
        String emailid = txtGuestEmail.getText();
        GuestQueries Insert= new GuestQueries();
        boolean res=Insert.CheckEmail(emailid);
        if(res==false)
        {
            JOptionPane.showMessageDialog(this, "This Email Id dosen't exists.");
        }
    }//GEN-LAST:event_txtGuestEmailFocusLost

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblDriverName;
    private javax.swing.JLabel lblGuestEmail;
    private javax.swing.JLabel lblPickupLocation;
    private javax.swing.JLabel lblPickupTime;
    private javax.swing.JTextField txtGuestEmail;
    private javax.swing.JTextField txtPickupLocation;
    private javax.swing.JTextField txtPickupTime;
    // End of variables declaration//GEN-END:variables

    private void populateDriverName(){
    EmployeeQueries emp= new EmployeeQueries();
        try {
            for(String emp1: emp.getDriverName()){
                System.out.println(emp1);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ManageEmployeesJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
       //tur comboBoxDriver.setModel(new DefaultComboBoxModel<String>(Employee.driverName.toArray(new String[0])));
        
    }
}
