/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JPanel;

/**
 *
 * @author Shruti
 */
public class TravelJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TravelJPanel
     */
    public TravelJPanel() {
        initComponents();
    }
    public void switchPanels(JPanel panel){
            layeredPane.removeAll();
            layeredPane.add(panel);
            layeredPane.repaint();
            layeredPane.revalidate();
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layeredPane = new javax.swing.JLayeredPane();
        jPanel3 = new javax.swing.JPanel();
        btnSchedulePickup = new javax.swing.JButton();
        btnCityTour = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnDropDestination = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        layeredPane.setLayout(new java.awt.CardLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btnSchedulePickup.setBackground(new java.awt.Color(255, 153, 51));
        btnSchedulePickup.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btnSchedulePickup.setForeground(new java.awt.Color(255, 255, 255));
        btnSchedulePickup.setText("Schedule Pickup");
        btnSchedulePickup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSchedulePickupActionPerformed(evt);
            }
        });

        btnCityTour.setBackground(new java.awt.Color(255, 153, 51));
        btnCityTour.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btnCityTour.setForeground(new java.awt.Color(255, 255, 255));
        btnCityTour.setText("City Tour");
        btnCityTour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCityTourActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/travel2.jpg"))); // NOI18N

        btnDropDestination.setBackground(new java.awt.Color(255, 153, 51));
        btnDropDestination.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btnDropDestination.setForeground(new java.awt.Color(255, 255, 255));
        btnDropDestination.setText("Drop Destination");
        btnDropDestination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDropDestinationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(btnSchedulePickup)
                .addGap(54, 54, 54)
                .addComponent(btnCityTour)
                .addGap(43, 43, 43)
                .addComponent(btnDropDestination)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCityTour, btnDropDestination, btnSchedulePickup});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSchedulePickup, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCityTour, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDropDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(139, 139, 139))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCityTour, btnDropDestination, btnSchedulePickup});

        layeredPane.add(jPanel3, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(layeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(196, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(layeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSchedulePickupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSchedulePickupActionPerformed
        // TODO add your handling code here:
        SchedulePickupJPanel airportPickup = new SchedulePickupJPanel();
        switchPanels(airportPickup);
    }//GEN-LAST:event_btnSchedulePickupActionPerformed

    private void btnCityTourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCityTourActionPerformed
        // TODO add your handling code here:
        CityTourJPanel cityTour = new CityTourJPanel();
        switchPanels(cityTour);
    }//GEN-LAST:event_btnCityTourActionPerformed

    private void btnDropDestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDropDestinationActionPerformed
        // TODO add your handling code here:
        DropDestinationJPanel dropDestination = new DropDestinationJPanel();
        switchPanels(dropDestination);
    }//GEN-LAST:event_btnDropDestinationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCityTour;
    private javax.swing.JButton btnDropDestination;
    private javax.swing.JButton btnSchedulePickup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLayeredPane layeredPane;
    // End of variables declaration//GEN-END:variables
}
