/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import databaseconnection.EmployeeQueries;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import model.BookHouseKeeping;
import static model.BookHouseKeeping.bookedhousekeeper;
import model.Employee;

/**
 *
 * @author shubhimiradwal
 */
public class viewGuestHousekeepingJPanel extends javax.swing.JPanel {

    /**
     * Creates new form viewGuestHousekeepingJPanel
     */
    public viewGuestHousekeepingJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_booked_customer = new javax.swing.JTable();

        tbl_booked_customer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Email", "Guest Name", "Role"
            }
        ));
        jScrollPane1.setViewportView(tbl_booked_customer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_booked_customer;
    // End of variables declaration//GEN-END:variables

public void populateTable()  {
        DefaultTableModel model = (DefaultTableModel) tbl_booked_customer.getModel();
        model.setRowCount(0);
       // EmployeeQueries emp= new EmployeeQueries();
       for(BookHouseKeeping emp1: bookedhousekeeper){
           if(emp1.getRole().equalsIgnoreCase("HouseKeeping"))
           {
               Object[] row = new Object[4];
               row[0] = emp1;
               row[1] = emp1.getEmail();
               row[2] = emp1.getGuest_name();
               row[3] = emp1.getRole();
               model.addRow(row);
           }
       }
}

}
